trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  bkstrgrg: 'Strorage-RG'
  bkstrg: 'storageaccount308081'
  bkcontainer: 'usecase'
  bkstrgkey: 'function.tfstate'
  backendServiceArm: 'devpos-sc'

stages:
  - stage: Init
    jobs:
      - job: TerraformInit
        steps:
          - task: TerraformTaskV4@4
            displayName: Terraform Init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: '$(backendServiceArm)'
              backendAzureRmResourceGroupName: '$(bkstrgrg)'
              backendAzureRmStorageAccountName: '$(bkstrg)'
              backendAzureRmContainerName: '$(bkcontainer)'
              backendAzureRmKey: '$(bkstrgkey)'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Azure Function Sql'

  - stage: Validate
    dependsOn: Init
    jobs:
      - job: TerraformValidate
        steps:
          - task: TerraformTaskV4@4
            displayName: Terraform Validate
            inputs:
              provider: 'azurerm'
              command: 'validate'
              backendServiceArm: '$(backendServiceArm)'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Azure Function Sql'

  - stage: Plan
    dependsOn: Validate
    jobs:
      - job: TerraformPlan
        steps:
          - task: TerraformTaskV4@4
            displayName: Terraform Plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: '$(backendServiceArm)'
              commandOptions: '-var-file=terraform.tfvars -out=tfplan'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Azure Function Sql'

  - stage: Apply
    dependsOn: Plan
    jobs:
      - job: TerraformApply
        steps:
          - task: TerraformTaskV4@4
            displayName: Terraform Apply
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: '$(backendServiceArm)'
              commandOptions: '-input=false tfplan'
              workingDirectory: '$(System.DefaultWorkingDirectory)/Azure Function Sql'
