resource_group_name       = "myResourceGroup"
location                  = "Canada Central"
function_app_name         = "myfunctionapp12"
sql_server_name           = "mySQLServer"
sql_database_name         = "myDatabase"
sql_admin_username        = "sqladmin"
sql_admin_password        = "P@ssw0rd1234!"
