resource_group_name       = "Function-App-RG"
location                  = "eastus"
function_app_name         = "myFunctionApp7795"
sql_server_name           = "mySQLServer1210"
administrator_login       = "sqladmin"
administrator_password    = "P@ssw0rd1234!"
sql_database_name             = "myDatabase"
